name: Website Health & Telegram Notification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger

jobs:
  website-monitor:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check Website Status
      id: check_website
      run: |
        STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://your-website.com)
        echo "HTTP_STATUS=$STATUS" >> $GITHUB_ENV
        if [ "$STATUS" -ge 200 ] && [ "$STATUS" -lt 400 ]; then
          echo "✅ Website is up with status $STATUS"
        else
          echo "❌ Website is down or unreachable. Status: $STATUS"
          echo "down=true" >> $GITHUB_OUTPUT
        fi

    - name: Send Telegram Notification if Website is Down
      if: steps.check_website.outputs.down == 'true'
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        format: markdown
        message: |
          *🚨 Website Down Notification!*
          
          *Repository:* `${{ github.repository }}`
          *Event:* `${{ github.event_name }}`
          *Branch:* `${{ github.ref_name }}`
          *Commit:* `${{ github.sha }}`
          
          *Actor:* `${{ github.actor }}`
          *Status:* ❌ Website is down or unreachable
          *HTTP Code:* `${{ env.HTTP_STATUS }}`
          
          [View Action Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
